ifeq ($(CONFIG_MACH_ASUS_X00TD),y)
obj-$(CONFIG_COMMON_FP)	+= common_X00TD/
obj-$(CONFIG_CDFINGER_FP)	+= cdfinger_X00TD/
obj-$(CONFIG_GOODIX_FP)	+= goodix_X00TD/
else
obj-$(CONFIG_CDFINGER_FP)	+= cdfinger_X01BD/
obj-$(CONFIG_FOCALTECH_FP)	+= focaltech_X01BD/
endif
